### ISSUE TITLE
Flight fails when on special mount randomly after flight bar is empty

### ISSUE THREAD

**Issue by PiBuddy** [GrafNikola/fly-forever#1]
There seems to be some issue when on mounts besides the free Tulpar where an error message randomly says "you can't use the summon: xxxx skill right now" after your flight bar is empty and one of two things will happen. 1) you'll keep flying but then can't dismount once you land because you really aren't mounted any more but instead bugged or 2) your mount randomly disappears when this message pops up and you fall to your death.  All the forks of this code base suffer this issue.  I've tried contacting Terablecoder about this but no response on his discord.  I don't mind using the Tulpar, but i just wanted to make people aware of the issue and to be careful to not fall to your death.

**Comment by GrafNikola** [comment]
Used for two days. During this time, such problems have not arisen. Can not help much, mainly engaged in translation
